version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
    time: "07:00"
    timezone: "Europe/Berlin"
    day: "monday"
  reviewers:
  - "maxmoehl"
  commit-message:
    prefix: "dep"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    time: "07:00"
    timezone: "Europe/Berlin"
    day: "monday"

