###
GRPC localhost/tt.Tt/StopTimer

###
GRPC localhost/tt.Tt/StartTimer

{
  "project": "work",
  "task": "backlog",
  "tags": ["home"],
  "timestamp": "2022-03-03T08:00:00+02:00"
}

<> 2022-03-04T083550.OK.json
<> 2022-03-04T083235.OK.json