#!/usr/bin/env zsh

VERSION="${1}"
GIT_DIRTY=$([[ -n $(git status --porcelain) ]] && echo "-dirty")
GIT_COMMIT=$(git rev-parse HEAD | cut -c 1-7)

go build \
  -o dist/tt \
  -tags "json1" \
  -ldflags "-X main.version=${VERSION}-${GIT_COMMIT}${GIT_DIRTY}" \
  github.com/maxmoehl/tt/tt

go build \
  -o dist/tt-grc \
  -tags "json1 grpc" \
  -ldflags "-X main.version=${VERSION}-${GIT_COMMIT}${GIT_DIRTY}" \
  github.com/maxmoehl/tt/tt
