#!/usr/bin/env zsh

if [[ -z "${1}" ]]; then
  echo "please provide the version to install as first argument"
  exit 1
fi

VERSION="${1}"
GIT_COMMIT=$(git rev-parse "${VERSION}" | cut -c 1-7)

go install \
  -tags "json1" \
  -ldflags "-X main.version=${VERSION}-${GIT_COMMIT}" \
  "github.com/maxmoehl/tt/tt@${VERSION}"
